### ISSUE TITLE
help with starting to use Wikibase import

### ISSUE THREAD

**Issue by Rik44444** [filbertkm/WikibaseImport#47]
Hi, thanks for developing and maintaining this extension, it will be really really useful for me once i get it to work! 

So atm i'm getting an error. Steps to reproduce (i followed https://github.com/filbertkm/WikibaseImport):
- install Wikibase 1.34
- install Wikibaseimport extension (i tried cloning version 1.34, but got an error that did not exist, so went with the master)
- run composer update in WikibaseImport folder
- add wfLoadExtension( 'WikibaseImport' );  to LocalSettings.php
- run php maintenance/update.php
- import an example entity, e.g. Samsung from Wikidata: https://www.wikidata.org/wiki/Q20716 , by entering:
`~/mydomain/w/extensions/WikibaseImport $ phpmaintenance/importEntities.php --entity Q20716`

Expected result:
- import of item Q20716 from Wikidata to my Wikibase repo

Actual result:
- no import + following error: 

[1c3bcba28243820e0d31340f] [no req]   Error from line 155 of /home/mydomain/w/extensions/WikibaseImport/src/EntityImporter.php: Call to undefined method Wikibase\DataModel\Entity\Item::getSiteLinks()
Backtrace:
#0 /home/mydomain/w/extensions/WikibaseImport/src/EntityImporter.php(185): Wikibase\Import\EntityImporter->getBadgeItems(array)
#1 /home/mydomain/w/extensions/WikibaseImport/src/EntityImporter.php(69): Wikibase\Import\EntityImporter->importBadgeItems(array)
#2 /home/mydomain/w/extensions/WikibaseImport/maintenance/importEntities.php(78): Wikibase\Import\EntityImporter->importEntities(array)
#3 /home/mydomain/w/maintenance/doMaintenance.php(99): Wikibase\Import\Maintenance\ImportEntities->execute()
#4 /home/mydomain/w/extensions/WikibaseImport/maintenance/importEntities.php(133): require_once(string)
#5 {main}

I also have a **bonus question**: nowhere have i entered "wikidata.org", so how does the extension know that i want an item from WikiData? + How do i enter a different URL when i want to import items from a different Wiki repo?

**Comment by maxchu2021** [comment]
I've got this issue also.

I can only do "php maintenance/importEntities.php --all-properties" this one. But others have the same issue as above.

**Comment by danmichaelo** [comment]
This seems to be an actual compatibility issue.

The `Item::getSiteLinks()` method was *removed* in wikibase/data-model [8.0 (2018-08-03)](https://github.com/wmde/WikibaseDataModel/blob/master/RELEASE-NOTES.md#version-800-2018-08-03), so WikibaseImport needs to be updated to use `getSiteLinkList()` instead.

**Comment by danmichaelo** [comment]
Oh, and there is already a PR that fixes it: https://github.com/filbertkm/WikibaseImport/pull/45

**Comment by Rik44444** [comment]
is there anything i can do to help in getting this fixed?

**Comment by danmichaelo** [comment]
There is a working fork at https://github.com/Wikidata/WikibaseImport

**Comment by Rik44444** [comment]
ah brilliant! i will try that asap. many thanks @danmichaelo
